version: "3.1"

services:

    mongo:
        image: mongo
        container_name: db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        container_name: db-web
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: user
    server:
        container_name: server 
        command: python -m flask run -h 0.0.0.0
        environment:
            - FLASK_DEBUG=1
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        ports:
            - 5001:5000
        volumes:
            - ./server:/server
            - /etc/localtime:/etc/localtime

    client:
        restart: always
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - ./client:/client
        stdin_open: true